version: "3.9"

services:
  # db:
  #   container_name: db-mysql
  #   platform: linux/x86_64
  #   image: mysql:latest
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - "./mysql_db:/var/lib/mysql"
  #   environment:
  #    - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
  #   restart: always
  #   command: --default-authentication-plugin=mysql_native_password

  api:
    container_name: apache-php82-sqlsrv
    # platform: linux/x86_64
    build: .
    volumes:
      - ./www:/var/www/html/
    ports:
      - 8000:80
    depends_on:
      # - db-mysql
      - db-mssql

  db-mssql:
    container_name: db-mssql
    # platform: linux/x86_64
    image: mcr.microsoft.com/mssql/server
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Root@123"
      MSSQL_SA_PASSWORD: "Root@123"
      MSSQL_PID: "Developer"
    restart: always
    command: /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P "Root@123" -Q "CREATE DATABASE ferah;"
